# Generated by Django 4.0.3 on 2022-03-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_descrption_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_URL',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
